x-gui-vol: &gui-vol
  - /tmp/.X11-unix:/tmp/.X11-unix:rw

services:
###############################################################################
# interactive dev container
###############################################################################
  ur5_dev:
    build: .
    image: ur5_gazebo_motion_lib_api
    container_name: ur5_dev
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/ur5_sim:rw
    network_mode: host
    privileged: true
    shm_size: "2gb"
    working_dir: /ur5_sim/ws/
    tty: true
    entrypoint: ["/entrypoint.sh"]
    command: bash

###############################################################################
# Task 1 – sine‑wave demo
###############################################################################
  ur5_sine_demo:
    image: ur5_gazebo_motion_lib_api
    build: .
    container_name: ur5_sine_demo
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/ur5_sim:rw
    network_mode: host
    privileged: true
    shm_size: "2gb"
    working_dir: /ws
    tty: true
    entrypoint: ["/sine_demo_entrypoint.sh"]

###############################################################################
# Task 2 – motion server
###############################################################################
  ur5_motion_server:
    image: ur5_gazebo_motion_lib_api
    build: .
    container_name: ur5_motion_server
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_IP=127.0.0.1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/ur5_sim:rw
    network_mode: host
    privileged: true
    shm_size: "2gb"
    working_dir: /ws
    tty: true
    entrypoint: ["/motion_server_entrypoint.sh"]

###############################################################################
# Task 3 + 4 – MotionApi + LLM
###############################################################################
  ur5_llm:
    image: ur5_gazebo_motion_lib_api
    build: .
    container_name: ur5_llm
    depends_on: [ollama]
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - OLLAMA_HOST=http://localhost:11434
      - LLM_MODEL=phi4-reasoning 
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/ur5_sim:rw
    network_mode: host
    working_dir: /ws
    tty: true
    entrypoint: ["/llm_entrypoint.sh"]

###############################################################################
# Side‑car LLM server
###############################################################################
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama-phi4   # ← new
    image: ollama-with-phi4
    ports: ["11434:11434"]
    # volumes:
    #   - ollama-data:/root/.ollama
  
volumes:
  ollama-data:
